languageCode = "en-us"
title = "Diego Go"
baseurl = "https://dgoscn.github.io/cene-pa/"
publishDir = "docs"
theme = "aerial"

[params]
  name = "Diego Amaral"
  about = "Netsuite Developer &nbsp;&bull;&nbsp; Lifelong Learner &nbsp;&bull;&nbsp; Nerd Sometimes &nbsp;&bull;&nbsp; another site is comming ;)"
  copyright = "diegoamaral"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  #bg_scroll = "stop"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/diego.liard3"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/dgoscn"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/dje6o/"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/dgoscn"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/amaraldude/"
